general:

  # Polling cycle time (in seconds) to discover new ports.
  cycle_time: 10
  
  #number of commands (store, mstore) to add in the pipeline before executing them min: 1 max: 1000
  pipeline_length: 1000

  #flag to use the pipeline or not
  use_pipeline: true


redis:

  # Redis Server host of volatile instance
  host_volatile: "localhost"


  # Redis Server host of persistent instance
  host_persistent: "localhost"


  # Redis Server port of volatile instance
  port_volatile: 6379


  # Redis Server port of persistent instance
  port_persistent: 6380


  # Decode the response in Redis client response.
  decode_response: true


  # Instance type to use; policy for data storage: accepted values are:
  #      - VOLATILE: all databases are volatile
  #      - PERSISTENT: all databases are persistent
  #      - VOLATILE_PERSISTENT:
  #          volatile: data, reserved key, time series;
  #          persistent: device, persistent data, time series tags, settings;
  #
  instance_type: VOLATILE


  #  Number of connection attempts to Redis Server, one attempt every 3 second
  #      - No limits: -1
  #      - Default: 5
  connection_attempts: 5


  #  Time Series data retetion time. It's the maximum age for samples compared
  #      to last event time (in milliseconds)
  #
  #      - Default: 0 - The global retention secs configuration of the database.
  #          When set to 0, the series is not trimmed at all
  #      - 1 Minute: 60000
  #      - 12 Hours: 43200000
  #      - 1 Day: 86400000
  #      - 7 Days: 604800000
  #
  #      Note: Time Series data are usually stored in the volatile instance. If the device
  #          power off, you lose your data in any case.
  retetion: 3600000

  volatile:
    datastore_std_db: 0
    datastore_dev_db: 1
    datastore_per_db: 2
    datastore_rsvd_db: 3
    datastore_tse_db: 4
    datastore_tag_db: 5
    datastore_stng_db: 6

    host_volatile: "localhost"
    port_volatile: 6379

    host_persistent: "localhost"
    port_persistent: 6379


  persistent:
    datastore_std_db: 0
    datastore_dev_db: 1
    datastore_per_db: 2
    datastore_rsvd_db: 3
    datastore_tse_db: 4
    datastore_tag_db: 5
    datastore_stng_db: 6
    host_volatile: "localhost"
    port_volatile: 6380
    host_persistent: "localhost"
    port_persistent: 6380

  volatile_persistent:
    #volatile
    datastore_std_db: 0
    datastore_rsvd_db: 1
    datastore_tse_db: 2

    host_volatile: "localhost"
    port_volatile: 6379

    #persistent
    datastore_dev_db: 0
    datastore_per_db: 1
    datastore_tag_db: 2
    datastore_stng_db: 3

    host_persistent: "localhost"
    port_persistent: 6380


port:

  # Folder for firmware to be flashed onto microcontroller.
  firmware_path: "/tmp/arancino/firmware"


  # Allowed firmware file extensions
  firmware_file_types: ["bin", "hex", "uf2", "zip"]


  # Reset the port on connection.
  #   When the Daemon is restarted and the port are already connected means
  #   that the port already sent the START command, but Daemon loose the info
  #   due to the restart. so Arancino Daemon requires a reset of the
  #   microcontroller
  reset_on_connect: true


  # Reconnection delay after a reset (in seconds)
  #   When call the Reset function of a Port, the Daemon waits to
  #   do a new connection
  reset_reconnection_delay: 5


  # Command spawned when Upload function is called. The command
  #   could have one or more placeholders. Placeholders are all the
  #   attributes of the Port Class.
  upload_command: null


  port_type_list:
    - serial
    - test
    - mqtt
    - ble


  serial:
    
    # Enables discovery on serial port type
    discovery: true

    mcu_type_list:
      - samd21
      - nrf52
      - stm32
      - rp20


    # Automatically enables (and connect) a new discovered Port.
    auto_enable: true


    # It's a flag used by an UI, to make the Port showable or not
    #   Sets to true to make it not visible
    hide: false


    # Communication Baudrate
    comm_baudrate: 4000000


    # Reset Baudrate: Arancino Dameon opens a connection with this baudarate
    #  to reset the microcontroller. 'touch' reset.
    reset_baudrate: 300


    # Filter works with the below list (filter_list). Accepted filter
    #   type are: EXCLUDE, ONLY, ALL
    #   - EXCLUDE: excludes the ones in the filter_list.
    #   - ONLY: acceptes only the ones in the filter_list.
    #   - ALL: no filter, accepts all. This is the default filter type.
    filter_type: ALL


    # List parameters used in function of the filter_type
    #   for Serial Port the filter_list is list of VID:PID.
    #   Following the list of VID:PID of smartme.IO products
    #   - 0x04D8:0xECD9 - A1000 (aka Arancino Mignon) (SAMD21)
    #   - 0x04D8:0xECDA - E1000 (aka Arancino) (SAMD21)
    #   - 0x1915:0x521F - A3000 (aka Arancino Volante) (NRF52)
    #   - 0x2E8A:0x000A - A4000 (aka Arancino Pico) (RP2040)
    #   - 0x0483:0x5740 - A6000-A7000-A8000 (aka Arancino V*) (STM32)
    
    # Xs need to be upper-case
    filter_list:
      - "0X04D8:0XECD9"
      - "0X04D8:0XECDA"
      - "0X1915:0X521F"
      - "0X2E8A:0X000A"
      - "0X0483:0X5740"


    # Timeout in seconds in serial connection Min: 1
    timeout: 1


    # Command spawned when Upload function is called. The command
    #   could have one or more placeholders. Placeholders are all the
    #   attributes of the Port Class.
    #upload_command: "/usr/bin/run-arancino-bossac {port._device} {firmware}"


    # Reset the port on connection, override the default configuration (can be overrided by the mcu family)
    reset_on_connect: true


    # Reconnection delay after a reset (in seconds).
    reset_reconnection_delay: 40

    # Queue size for buffering commands
    queue_max_size: 1024

    # time (in seconds) between each heartbeat check
    heartbeat_rate: 5

    # time threshold (in milliseconds) between to heartbeat #1 and #2 used to evaluate the healty of the system
    heartbeat_time: 10

    # number of heartbeat checks, when no heartbeat is detected, before send alert.
    heartbeat_attempts: 5


    # Specific configurations for the SAMD21 microcontoller.
    samd21:
      list: #list of possible vid:pid
        - "0X04D8:0XECDA"
        - "0X04D8:0XECD9"
      upload_command: "/usr/bin/run-arancino-bossac {port._device} {firmware}"
      reset_on_connect: true
      reset_reconnection_delay: 5
      comm_baudrate: 4000000


    # Specific configurations for the NRF52 microcontoller.
    nrf52:
      list: #list of possible vid:pid
        - "0X1915:0X521F"
      upload_command: "/usr/bin/adafruit-nrfutil dfu serial -pkg {firmware} -p {port._device} -b 115200 --singlebank"
      reset_on_connect: true
      reset_reconnection_delay: 40
      comm_baudrate: 256000


    # Specific configurations for the STM32 microcontoller.
    stm32:
      list: #list of possible vid:pid
        - "0X0483:0X5740"
      upload_command: "/usr/bin/run-arancino-arduinoSTM32load {port._device} {firmware}"
      reset_on_connect: true
      reset_reconnection_delay: 5
      comm_baudrate: 256000


    # Specific configurations for the RP20 microcontoller.
    rp20:
      list: #list of possible vid:pid
        - "0X2E8A:0X000A"
      upload_command: "/usr/bin/run-arancino-uf2conv {port._device} {firmware}"
      reset_on_connect: true
      reset_reconnection_delay: 5
      comm_baudrate: 256000


  test:

    discovery: false

    auto_enable: true

    hide: false

    filter_type: ALL

    filter_list: null

    reset_on_connect: false

    upload_command: null


    # The number of Port to create for test purpose
    num: 0

    # Delay between each command in seconds (accepts float)
    delay: 5


    # prefix of the id generated for the test port
    id_template: TESTPORT

    # time (in seconds) between each heartbeat check
    heartbeat_rate: 5

    # time threshold (in milliseconds) between to heartbeat #1 and #2 used to evaluate the healty of the system
    heartbeat_time: 10

    # number of heartbeat checks, when no heartbeat is detected, before send alert.
    heartbeat_attempts: 5


  mqtt:

  
    # Enables discovery on mqtt port type
    discovery: false

    # Automatically enables (and connect) a new discovered Port.
    auto_enable: true


    # It's a flag used by an UI, to make the Port showable or not
    #   Sets to true to make it not visible
    hide: false


    # Reset port on connection
    reset_on_connect: false

    filter_type: "ALL"
    filter_list: []

    # ! Issue : 123
    # queue_size : 8

    # Mqtt-Bus Broker Connection Parameters
    connection:

      host: localhost
      port: 1883
      username: arancino-daemon
      password: 12345678

      use_tls: false
      ca_path : ""
      cert_path: ""
      key_path: ""

      # Topic that will be used for discovery process
      discovery_topic: arancino/discovery
      # Topic that will be used for both send and receive (in relative subtopics)
      cortex_topic: arancino/cortex
      # Topic that will be used for mcu reset process
      service_topic: arancino/service

    # time (in seconds) between each heartbeat check
    heartbeat_rate: 5

    # time threshold (in milliseconds) between to heartbeat #1 and #2 used to evaluate the healty of the system
    heartbeat_time: 100

    # number of heartbeat checks, when no heartbeat is detected, before send alert.
    heartbeat_attempts: 5

  uart_ble:

    # Enables discovery on mqtt port type
    discovery: false

    # Automatically enables (and connect) a new discovered Port.
    auto_enable: true


    # It's a flag used by an UI, to make the Port showable or not
    #   Sets to true to make it not visible
    hide: false


    # Reset port on connection
    reset_on_connect: true

    filter_type: ALL
    filter_list: []

    # command to be spawn when upload api is called. The command could have one or more placeholders.
    upload_command: nrfutil ...
    # time (in seconds) between each heartbeat check
    heartbeat_rate: 5

    # time threshold (in milliseconds) between to heartbeat #1 and #2 used to evaluate the healty of the system
    heartbeat_time: 200

    # number of heartbeat checks, when no heartbeat is detected, before send alert.
    heartbeat_attempts: 5

    # Timeout in seconds in connection. Min: 1
    timeout: 10

    # size for Tx and Rx UartBle buffers
    buffer_size: 1024

    services:

      # name for service tx characteristic of device
      vendor_communication_uuid: 6E400001-B5A3-F393-E0A9-E50E24DCCA9E

      # name for tx characteristic of device
      vendor_tx_uuid: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E

      # name for rx characteristic of device
      vendor_rx_uuid: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E

      # name for service tx characteristic of device
      vendor_service_uuid: 01010101-0101-0101-0101-010101010101

      # name for service tx characteristic of device
      vendor_service_tx_uuid: 01010003-B5A3-F393-E0A9-E50E24DCCA9E

      # name for service rx characteristic of device
      vendor_service_rx_uuid: 01010002-B5A3-F393-E0A9-E50E24DCCA9E


log:

  # Log Level for the Logger. Accetpted values are:
  #   - ERROR
  #   - WARNING
  #   - INFO
  #   - DEBUG
  level: DEBUG


  # Name to print with the logger
  name: Arancino


  # Available Log Handlers, sets to true to enable or false to disable
  # Console Handler
  handler_console: true


  # File Handler
  handler_file: true


  # Size in MBytes only for the handler_file. Min: 1, Max: 5, Default: 1
  size: 1

  # Number of files to use in rotate mode. Min: 1, Max: 10, Default: 1
  rotate: 1

  # Names of log files
  # Standard Log File
  file_log: arancino.log


  # Error Log File
  file_error: arancino.error.log


  # Enables or disables printing of stack trace on errors
  print_stack_trace: true
