flow:
  name: StatsFlow
  enabled: true

parser:
  class: ParserS4T
  section:
    - simple
    - s4t
    - parser
  file: STATS_default.json.tmpl

  simple: null
  # Configuration for ParserSimple

  s4t:
  # Configuration for ParserS4T

    db_name: sme_sandbox

sender:
# Available Senders are: SenderDoNothing, SenderTcpSocket, SenderMqtt, SenderMqttS4T
  class: SenderMqttS4T
  section:
    - mqtt
    - mqtts4t
    - sender

  mqtt:
    use_tls: false
    qos: 1
    retain: false

    # NOTE: non available at the moment.
    # channel parameter can contains placeholder with the using of "{" and "}"
    # placeholder can be:
    #   - key -> the name of the key that contains the measurements
    #   - labels.port_id -> the identifier of the port that provides the measurements
    #   - labels.port_type -> the type of the port that provides the measurements
    #   - labels.device_id -> the identifier of the device where the ports are connected to. (Note: not always available)
    #   - labels.?????

    topic: your_topic

    # plain
    host: server.smartme.io
    port: 1883
    username: arancini
    password: smartme

    # secure
    ca_path: null
    cert_path: null
    key_path: null

  mqtts4t: null