flow:
  name: Test
  enabled: true

parser:
  class: ParserSimple
  section:
    - simple
    - parser
  file: default.json.tmpl

  simple: null
    # Configuration for ParserSimple

sender:
# Available Senders are: SenderDoNothing, SenderTcpSocket, SenderMqtt, SenderMqttS4T
  class: SenderTcpSocket
  section:
    - tcpsocket
    - sender

  tcpsocket:
    host: localhost
    port: 1122